config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:index]

  root "home#index"
  
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Blog', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Posts', posts_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
aria-expanded="false">
            <% if user_signed_in? %>
              <% if current_user.name %>
                Hola <%= current_user.name %>
              <% else %>
                Hola <%= current_user.email%>
              <% end %>
            <% else %>
              Dale registrate o conectate
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item',
method: :delete %></li>
            <% else %>
              <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item'%></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item'%></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>